# Generated by Django 5.0 on 2024-01-13 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_news_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='img',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='news/'),
        ),
    ]
